/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import rock_papar_scissors.RockPaparScissors;

public class App {
    public static void main(String[] args) {
        RockPaparScissors rsp = new RockPaparScissors("大稀");
        rsp.run();
    }
}
