/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.*;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.Group;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.event.EventHandler;
import javafx.scene.input.MouseEvent;
import game.tic_tac_toe.TicTacToe;

public class App extends Application{
    @Override
    public void start(Stage primaryStage) {

        Canvas canvas = new Canvas(300, 300);
        GraphicsContext gc = canvas.getGraphicsContext2D();

        EventHandler<MouseEvent> handler = (MouseEvent e) -> {
            System.out.println(String.valueOf(e.getX()) + String.valueOf(e.getY()));
        };
        canvas.addEventHandler(MouseEvent.MOUSE_PRESSED, handler);

        gc.save();
        gc.setLineWidth(2);
        gc.strokeLine(0, 100, 300, 100);
        gc.strokeLine(0, 200, 300, 200);
        gc.strokeLine(100, 0, 100, 300);
        gc.strokeLine(200, 0, 200, 300);
        gc.restore();

        Group root = new Group();
        root.getChildren().add(canvas);

        primaryStage.setTitle("まるばつゲーム");
        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }

    public static void main(String... args) {
        Application.launch(args);
    }
}
