/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import game.*;
// import game.util.*;
import game.tic_tac_toe.*;

public class AppTest {
    @Test
    public void testBoard (){
        Board target = new Board(3);
        System.out.println(target.toString());
        target.changeColor(1, 1, Color.BLACK);
        System.out.println(target.toString());
    }
}
