/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import game.*;
// import game.util.*;
import game.tic_tac_toe.*;

public class AppTest {
    @Test
    public void testBoard (){
        Board target = new Board(3);
        target.changeColor(0, 0, Color.BLACK);
        // assertEquals(false, target.whetherWin(0, 0, Color.BLACK));
    }
}
